import Head from "../node_modules/next/head";

export default function Home(): JSX.Element {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        aaa
      </main>

      <footer >

      </footer>
    </div>
  );
}
